// Generated by CoffeeScript 1.6.3
(function() {
  var main;

  main = angular.module('RPS', ['ui.bootstrap']).config(function($routeProvider) {
    return $routeProvider.when('/name', {
      templateUrl: 'partials/name.html',
      controller: 'AskName'
    }).when('/choice', {
      templateUrl: 'partials/choice.html',
      controller: 'ChooseRPS'
    }).otherwise({
      redirectTo: '/name'
    });
  });

  angular.module('RPS').controller('ChooseRPS', function($scope) {
    return $scope.images = {
      'rock': {
        image: 'static/rock.svg'
      },
      'paper': {
        image: 'static/paper.svg'
      },
      'scissors': {
        image: 'static/scissors.svg'
      }
    };
  });

  angular.module('RPS').controller('AskName', function($scope) {
    $scope.question = 'Hello, what is your name?';
    $scope.name = 'Player';
    return $scope.submit = function() {
      return alert('this is the part where I change the view...');
    };
  });

}).call(this);
