// Generated by CoffeeScript 1.6.3
(function() {
  var main;

  main = angular.module('myApp', []).controller('MainController', function($scope) {
    return $scope.name = 'Player';
  });

}).call(this);
