// Generated by CoffeeScript 1.6.3
(function() {
  var main;

  main = angular.module('RPS', []);

  angular.module('RPS').controller('AskForName', function($scope) {
    $scope.name = "Player";
    return $scope.submit = function() {
      alert('submitted!');
      return $scope.greeting = "Hello " + $scope.name + "! Let's play Rock Paper Scissors...";
    };
  });

  angular.module('RPS').controller('ChooseRPS', function($scope) {
    return $scope.choice = "";
  });

}).call(this);
