// Generated by CoffeeScript 1.6.3
(function() {
  var express, fs, port, rps, text;

  express = require('express');

  fs = require('fs');

  rps = express(express.logger());

  rps.use(express["static"](__dirname + '/static'));

  text = fs.readFileSync('index.html');

  rps.get('/', function(request, response) {
    response.writeHead(200);
    response.write(text);
    return response.end();
  });

  port = process.env.PORT || 8080;

  rps.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
